- hosts: all
  become: yes

  tasks:
    # Optimization
    - name: Clean Up
      script: /vagrant/provision/scripts/cleanup.sh

    - name: Minimize
      script: /vagrant/provision/scripts/minimize.sh